<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);UOMG002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/UO.Mediator.Shared/UO.Mediator.Shared.csproj" />
    <ProjectReference Include="../../src/UO.Mediator.Generators/UO.Mediator.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
