<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../UO.Mediator.MultiAssembly.Contracts/UO.Mediator.MultiAssembly.Contracts.csproj" />
    <ProjectReference Include="../../src/UO.Mediator/UO.Mediator.csproj" />
    <ProjectReference Include="../../src/UO.Mediator.Generators/UO.Mediator.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
