<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/UO.Mediator.Generators/UO.Mediator.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/UO.Mediator/UO.Mediator.csproj" />
    <ProjectReference Include="../UO.Mediator.Startup10/UO.Mediator.Startup10.csproj" />
    <ProjectReference Include="../UO.Mediator.Startup100/UO.Mediator.Startup100.csproj" />
    <ProjectReference Include="../UO.Mediator.Startup1000/UO.Mediator.Startup1000.csproj" />
  </ItemGroup>

</Project>
