<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../UO.Mediator.MultiAssembly.Contracts/UO.Mediator.MultiAssembly.Contracts.csproj" />
    <ProjectReference Include="../UO.Mediator.MultiAssembly.HandlersA/UO.Mediator.MultiAssembly.HandlersA.csproj" />
    <ProjectReference Include="../UO.Mediator.MultiAssembly.HandlersB/UO.Mediator.MultiAssembly.HandlersB.csproj" />
    <ProjectReference Include="../../src/UO.Mediator/UO.Mediator.csproj" />
  </ItemGroup>

</Project>
